"""empty message

Revision ID: 35f917e45a77
Revises: 
Create Date: 2021-04-25 22:46:19.622743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35f917e45a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Performance',
    sa.Column('Movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_fee', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Actor_id'], ['actors.id'], name='Performance_Actor_id_fkey'),
    sa.ForeignKeyConstraint(['Movie_id'], ['movies.id'], name='Performance_Movie_id_fkey')
    )
    # ### end Alembic commands ###
